cache:
  paths:
  - vendor/

before_script:
- apt-get update -y
- apt-get install -qqy git unzip wget libxml2-dev
- pecl install xdebug
- docker-php-ext-enable xdebug
- docker-php-ext-install -j$(nproc) soap
#download sonar scanner
- wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip
- unzip ./sonar-scanner.zip
#install node to allow css analysis
- curl -sL https://deb.nodesource.com/setup_10.x > setup_10.x
- chmod +x setup_10.x
- ./setup_10.x
- apt-get install -qqy nodejs
- wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
- php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
- php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
- php composer-setup.php
- php -r "unlink('composer-setup.php'); unlink('installer.sig');"
- php composer.phar install --no-interaction --prefer-dist
- wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${CERTPATH}" -O cert.pem
- sed -e "s?PASSPHRASE?$(echo $PASSPHRASE | sed -e 's/\\/\\\\/g; s/\//\\\//g; s/&/\\\&/g')?" --in-place tests/config.php
- sed -e "s?PROXYPORT?$PROXYPORT?" --in-place tests/config.php
- sed -e "s?PROXYHOST?$PROXYHOST?" --in-place tests/config.php

test:7.4:NM235:
  image: php:7.4
  stage: test
  script:
    - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH235}" -O wsdl235.zip
    - unzip wsdl235.zip
    - sed -e "s?VERSION?23.5.0?" --in-place tests/config.php
    - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_23.5.0.wsdl?" --in-place tests/config.php
    - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_23.5.0.wsdl?" --in-place tests/config.php
    - vendor/bin/phpunit --coverage-text --colors=never
    - ./sonar-scanner-4.0.0.1744-linux/bin/sonar-scanner -Dsonar.login=${SONAR_TOKEN}

test:7.4:NM230:
  image: php:7.4
  stage: test
  script:
    - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH230}" -O wsdl230.zip
    - unzip wsdl230.zip
    - sed -e "s?VERSION?23.0.0?" --in-place tests/config.php
    - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_23.0.0.wsdl?" --in-place tests/config.php
    - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_23.0.0.wsdl?" --in-place tests/config.php
    - vendor/bin/phpunit --coverage-text --colors=never

test:7.4:NM225:
  image: php:7.4
  stage: test
  script:
    - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH225}" -O wsdl225.zip
    - unzip wsdl225.zip
    - sed -e "s?VERSION?22.5.0?" --in-place tests/config.php
    - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_22.5.0.wsdl?" --in-place tests/config.php
    - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_22.5.0.wsdl?" --in-place tests/config.php
    - vendor/bin/phpunit --coverage-text --colors=never

test:7.4:NM220:
  image: php:7.4
  stage: test
  script:
    - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH220}" -O wsdl220.zip
    - unzip wsdl220.zip
    - sed -e "s?VERSION?22.0.0?" --in-place tests/config.php
    - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_22.0.0.wsdl?" --in-place tests/config.php
    - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_22.0.0.wsdl?" --in-place tests/config.php
    - vendor/bin/phpunit --coverage-text --colors=never

test:7.3:NM235:
  image: php:7.3
  stage: test
  script:
    - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH235}" -O wsdl235.zip
    - unzip wsdl235.zip
    - sed -e "s?VERSION?23.5.0?" --in-place tests/config.php
    - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_23.5.0.wsdl?" --in-place tests/config.php
    - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_23.5.0.wsdl?" --in-place tests/config.php
    - vendor/bin/phpunit --coverage-text --colors=never

test:7.3:NM230:
  image: php:7.3
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH230}" -O wsdl230.zip
  - unzip wsdl230.zip
  - sed -e "s?VERSION?23.0.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_23.0.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_23.0.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.3:NM225:
  image: php:7.3
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH225}" -O wsdl225.zip
  - unzip wsdl225.zip
  - sed -e "s?VERSION?22.5.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_22.5.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_22.5.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.3:NM220:
  image: php:7.3
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH220}" -O wsdl220.zip
  - unzip wsdl220.zip
  - sed -e "s?VERSION?22.0.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_22.0.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_22.0.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.2:NM235:
  image: php:7.2
  stage: test
  script:
    - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH235}" -O wsdl235.zip
    - unzip wsdl235.zip
    - sed -e "s?VERSION?23.5.0?" --in-place tests/config.php
    - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_23.5.0.wsdl?" --in-place tests/config.php
    - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_23.5.0.wsdl?" --in-place tests/config.php
    - vendor/bin/phpunit --coverage-text --colors=never

test:7.2:NM230:
  image: php:7.2
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH230}" -O wsdl230.zip
  - unzip wsdl230.zip
  - sed -e "s?VERSION?23.0.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_23.0.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_23.0.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.2:NM225:
  image: php:7.2
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH225}" -O wsdl225.zip
  - unzip wsdl225.zip
  - sed -e "s?VERSION?22.5.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_22.5.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_22.5.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.2:NM220:
  image: php:7.2
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH220}" -O wsdl220.zip
  - unzip wsdl220.zip
  - sed -e "s?VERSION?22.0.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_22.0.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_22.0.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never