cache:
  paths:
  - vendor/

before_script:
- export http_proxy=http://10.196.32.91:3142
- apt-get update -y
- apt-get install -qqy git unzip wget libxml2-dev
- pecl install xdebug
- docker-php-ext-enable xdebug
- docker-php-ext-install -j$(nproc) soap
- wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
- php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
- php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
- php composer-setup.php
- php -r "unlink('composer-setup.php'); unlink('installer.sig');"
- php composer.phar install --no-interaction --prefer-dist
- wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${CERTPATH}"
- sed -e "s?PASSPHRASE?$(echo $PASSPHRASE | sed -e 's/\\/\\\\/g; s/\//\\\//g; s/&/\\\&/g')?" --in-place tests/config.php
- sed -e "s?PROXYPORT?$PROXYPORT?" --in-place tests/config.php
- sed -e "s?PROXYHOST?$PROXYHOST?" --in-place tests/config.php

test:7.1:NM215:
  image: php:7.1
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH215}"
  - unzip wsdl215.zip
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_21.5.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_21.5.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.1:NM210:
  image: php:7.1
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH210}"
  - unzip wsdl210.zip
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_21.5.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_21.5.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never