cache:
  paths:
  - vendor/

before_script:
- apt-get update -y
- apt-get install -qqy git unzip wget libxml2-dev
- pecl install xdebug
- docker-php-ext-enable xdebug
- docker-php-ext-install -j$(nproc) soap
- wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
- php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
- php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
- php composer-setup.php
- php -r "unlink('composer-setup.php'); unlink('installer.sig');"
- php composer.phar install --no-interaction --prefer-dist
- wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${CERTPATH}"
- sed -e "s?PASSPHRASE?$(echo $PASSPHRASE | sed -e 's/\\/\\\\/g; s/\//\\\//g; s/&/\\\&/g')?" --in-place tests/config.php
- sed -e "s?PROXYPORT?$PROXYPORT?" --in-place tests/config.php
- sed -e "s?PROXYHOST?$PROXYHOST?" --in-place tests/config.php

test:7.3:NM230:
  image: php:7.3
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH230}"
  - unzip wsdl230.zip
  - sed -e "s?VERSION?23.0.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_23.0.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_23.0.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.3:NM225:
  image: php:7.3
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH225}"
  - unzip wsdl220.zip
  - sed -e "s?VERSION?22.5.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_22.5.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_22.5.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.3:NM220:
  image: php:7.3
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH220}"
  - unzip wsdl220.zip
  - sed -e "s?VERSION?22.0.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_22.0.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_22.0.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.3:NM215:
  image: php:7.3
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH215}"
  - unzip wsdl215.zip
  - sed -e "s?VERSION?21.5.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_21.5.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_21.5.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.2:NM230:
  image: php:7.2
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH230}"
  - unzip wsdl220.zip
  - sed -e "s?VERSION?23.0.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_23.0.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_23.0.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.2:NM225:
  image: php:7.2
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH225}"
  - unzip wsdl225.zip
  - sed -e "s?VERSION?22.5.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_22.5.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_22.5.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.2:NM220:
  image: php:7.2
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH220}"
  - unzip wsdl220.zip
  - sed -e "s?VERSION?22.0.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_22.0.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_22.0.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never

test:7.2:NM215:
  image: php:7.2
  stage: test
  script:
  - wget --header "PRIVATE-TOKEN:${ACCESSTOKEN}" "${WSDLPATH215}"
  - unzip wsdl215.zip
  - sed -e "s?VERSION?21.5.0?" --in-place tests/config.php
  - sed -e "s?AIRSPACESERVICESWSDL?AirspaceServices_PREOPS_21.5.0.wsdl?" --in-place tests/config.php
  - sed -e "s?FLOWSERVICESWSDL?FlowServices_PREOPS_21.5.0.wsdl?" --in-place tests/config.php
  - vendor/bin/phpunit --coverage-text --colors=never